<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find yobotics_description)/xacro/transmission.xacro"/>

    <xacro:macro name="leg" params="name mirror mirror_dae front_hind front_hind_dae *origin">


<!-- //////////////////////hip//////////////////// -->
        <joint name="${name}_hip_joint" type="revolute">
        <!-- <joint name="${name}_hip_joint" type="continuous"> -->
            <xacro:insert_block name="origin"/>
            <parent link="trunk"/>
            <child link="${name}_hip"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${hip_min*PI/180.0}" upper="${hip_max*PI/180.0}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${-hip_max*PI/180.0}" upper="${-hip_min*PI/180.0}"/>
            </xacro:if>            
        </joint>

        <link name="${name}_hip">
            <visual>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="0 ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="package://yobotics_description/meshes/hip.STL" scale="1 1 1"/>
                </geometry>
                <material name="gold"/>
            </visual>
            <collision>
                <!-- <origin rpy="${PI/2.0} 0 0" xyz="0 0 0"/> -->
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="${PI} 0 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="0 ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="package://yobotics_description/meshes/hip.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${hip_com_x*front_hind} ${hip_com_y*mirror} ${hip_com_z}"/>
                <mass value="${hip_mass}"/>
                <inertia
                    ixx="${hip_ixx}" ixy="${hip_ixy*mirror*front_hind}" ixz="${hip_ixz*front_hind}"
                    iyy="${hip_iyy}" iyz="${hip_iyz*mirror}"
                    izz="${hip_izz}"/>       
            </inertial>
        </link>

       
<!-- //////////////////////thigh//////////////////// -->

        <joint name="${name}_thigh_joint" type="revolute">
         <!-- <joint name="${name}_thigh_joint" type="continuous"> -->
        
            <origin rpy="0 0 0" xyz="0 ${-thigh_offset*mirror} 0"/>
            <parent link="${name}_hip"/>
            <child link="${name}_thigh"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}" lower="${thigh_min*PI/180.0}" upper="${thigh_max*PI/180.0}"/>
             
        </joint>

        <link name="${name}_thigh">      
            <visual>
                <xacro:if value="${mirror_dae == True}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>                 
                </xacro:if>
                <xacro:if value="${mirror_dae == False}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="package://yobotics_description/meshes/thigh.STL" scale="1 1 1"/>
                </geometry>
                <material name="white_blue"/>
            </visual>
            <collision>
                 <xacro:if value="${mirror_dae == True}">
                    <origin rpy="0 0 0" xyz="0 0 0"/>                 
                </xacro:if>
                <xacro:if value="${mirror_dae == False}">
                    <origin rpy="${PI} ${PI} 0" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="package://yobotics_description/meshes/thigh.STL" scale="1 1 1"/>
                     
                </geometry>    
                <material name="white_blue"/>  
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${thigh_com_x} ${thigh_com_y*mirror} ${thigh_com_z}"/>
                <mass value="${thigh_mass}"/>
                <inertia
                    ixx="${thigh_ixx}" ixy="${thigh_ixy*mirror}" ixz="${thigh_ixz}"
                    iyy="${thigh_iyy}" iyz="${thigh_iyz*mirror}"
                    izz="${thigh_izz}"/>       
            </inertial>
        </link>

<!-- //////////////////////calf//////////////////// -->
        <joint name="${name}_calf_joint" type="revolute">
        <!-- <joint name="${name}_calf_joint" type="continuous"> -->
            <origin rpy="0 0 0" xyz="0 ${calf_offset_y} ${-thigh_length}"/>
            <parent link="${name}_thigh"/>
            <child link="${name}_calf"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <!-- <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${calf_min*PI/180.0}" upper="${calf_max*PI/180.0}"/> -->

            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="-${PI}" upper="${PI}"/>
        </joint>

        <link name="${name}_calf">
            <visual>           
                <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://yobotics_description/meshes/calf.STL" scale="1 1 1"/>
                </geometry>
                <material name="white_blue"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0.0 0.0 0.0" />
                <geometry>
                    <mesh filename="package://yobotics_description/meshes/calf.STL" scale="1 1 1"/>
                </geometry>      
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${calf_com_x} ${calf_com_y} ${calf_com_z}"/>
                <mass value="${calf_mass}"/>
                <inertia
                    ixx="${calf_ixx}" ixy="${calf_ixy}" ixz="${calf_ixz}"
                    iyy="${calf_iyy}" iyz="${calf_iyz}"
                    izz="${calf_izz}"/>       
            </inertial>
        </link>


<!-- //////////////////////foot//////////////////// -->
        <joint name="${name}_foot_fixed" type="fixed">
            <origin rpy="0 0 0" xyz="0 ${foot_offset_y} ${-(calf_length)}"/>     
            <parent link="${name}_calf"/>
            <child link="${name}_foot"/>
        </joint>

        <link name="${name}_foot">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                     <mesh filename="package://yobotics_description/meshes/foot.STL" scale="1 1 1"/>
                </geometry>
                <material name="white_black"/>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="package://yobotics_description/meshes/foot.STL" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${foot_com_x} ${foot_com_y} ${foot_com_z}"/>
                <mass value="${foot_mass}"/>
                <inertia
                    ixx="${foot_ixx}" ixy="${foot_ixy}" ixz="${foot_ixz}"
                    iyy="${foot_iyy}" iyz="${foot_iyz}"
                    izz="${foot_izz}"/>                 
            </inertial>
        </link>

        <xacro:leg_transmission name="${name}"/>
    </xacro:macro>
</robot>
